### ISSUE TITLE
Nice repo !

### ISSUE THREAD

**Issue by ghost** [skyeto/yara-rules#1]
The whole "injector" source code is stored in plain text in the binary so finding IOC shouldn't be complicated

**Comment by skyeto** [comment]
Hey, vercel/pkg packing was fun to reverse since it used brotli compression and created a virtual file system - I got a nice tool out of it and it took like an hour. Otherwise yea, it's easy to use signature based detection on your new version.

In any case, if you want to discuss anything I'd be happy to take it over another channel that is more appropriate than a GitHub issue. But to be honest, I think you've seen what my thoughts are on if it's "educational" or not, but who am I to judge. I'll just leave it at saying that your time is better spent on at least learning how to use Git properly.
